[package]
name = "writhe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colour = "0.7.0"
chrono = "0.4.26"
confy = "0.5.1"
serde_derive = "1.0.171"
serde = "1.0.171"